brews:
  - name: "starport"
    description: "CLI tool for developing Cosmos SDK apps."
    homepage: "https://github.com/CosmicCompass/starport"
    github:
      owner: "tendermint"
      name: "homebrew-tap"
    install: |
      bin.install "starport"
